# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/literate-en-fr-translation-service',
                'doc_host': 'https://fgiasson.github.io',
                'git_url': 'https://github.com/fgiasson/literate-en-fr-translation-service',
                'lib_path': 'literate_en_fr_translation_service'},
  'syms': { 'literate_en_fr_translation_service.core': { 'literate_en_fr_translation_service.core.foo': ( 'core.html#foo',
                                                                                                          'literate_en_fr_translation_service/core.py')}}}
