name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
     - name: Setup quarto-gh with Python 10
       uses: fastai/workflows/quarto-ghp@master
       with:
         version: '3.10' # python version to use for this step       

