name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
     - name: Setup nbdev-ci with Python 10
       uses: fastai/workflows/nbdev-ci@master
       with:
         # Semantic version range syntax or exact version of a Python version
         python-version: '3.10'
         # Optional - x64 or x86 architecture, defaults to x64
         architecture: 'x64'